### ISSUE TITLE
라우팅 및 구조 수정

### ISSUE THREAD

**Issue by lionleeee** [f-lab-edu/vanilla-figma-spa#5]
## TODO
 - [x]  파일명 오류 수정 및 중복 삭제
 - [x]  폴더명 규칙 수정
 - [x]  기능 위주 폴더구조 변경
 - [x]  콘텐츠 담당 컴포넌트 생성
 - [x] button, input 컴포넌트
 - [x] 레이아웃 확장성 고려
 - [x] 라우트 관련 코드 명확히 분리
