### ISSUE TITLE
캔버스 기능

### ISSUE THREAD

**Issue by lionleeee** [f-lab-edu/vanilla-figma-spa#7]
## TODO
 - [x]  캔버스 컴포넌트 생성
 - [x]  각 요소 동적 생성 기능
 - [x]  요소 생성 시 레이어 추가
